baseURL = '/'
languageCode = 'en-us'
title = 'Bob Rockefeller Photography'
copyright = "Â© Bob Rockefeller"
timeZone = "America/New_York"

theme = ['gallery']

[params]
  defaultTheme = "dark"
  [params.socialIcons]
  #   facebook = "https://www.facebook.com/"
  #   instagram = "https://www.instagram.com/"
  email = "photos@bobrockefeller.com"
  flickr = "https://www.flickr.com/photos/bobrocke/"
  fivehundredpx = "https://500px.com/p/BobRockefeller"

[imaging]
  quality = 90
